🧩 NumPy Mini Challenge: Student Marks Dashboard
🎯 Scenario:
You're given a flat array of marks for 4 students in 5 subjects. Each student has marks for Math, English, Physics, Chemistry, and History.

📦 Step-by-Step Tasks:
✅ Step 1: Create the array
Create a 1D array of 20 integers (marks between 50–100) and reshape it to shape (4, 5)
➡️ Shape = (4 students, 5 subjects)

✅ Step 2: Print student-wise data
Print marks of each student clearly.

✅ Step 3: Print subject-wise average marks
Calculate and print the average mark in each subject (column-wise average)

✅ Step 4: Find the highest total scorer
Find the student (row) with the highest total marks.

✅ Step 5: Curve the marks
Add 5 bonus marks to all students' marks, but don't let any value exceed 100
➡️ Use broadcasting + np.clip()

✅ Step 6: Check view vs copy
Make a slice of a student's marks, modify it, and see if it changes the original array.
Then do the same using .copy() and confirm the difference.

In [23]:
import numpy as np 
marks=np.random.randint(50,100,size=20).reshape(4,5)
print ("Marks of each student (student * marks) :",marks)
for i in range(4):
    print(f"Student{i+1} has score {marks[i]}")
col_wise= marks.mean(axis=0)
print("Subject wise or column wise  average marks of students are:",col_wise)
total_marks=marks.sum(axis=1)
top_scorrer_index=np.argmax(total_marks)
print(f"Student {top_scorrer_index+1} has top score {total_marks[top_scorrer_index]}")
curve=np.clip(marks+5,0,100)
print("Marks of all the student = ",curve)
slice_view=marks[0][1:4]
print("The slice of the marks array is",marks[0])
slice_view[0]=83
print("Now see the changes in the original marks array",marks[0]," \nSo the slice_view is the view and it values changes")
slice_view=marks[0][1:4].copy()
slice_view[0]=88
print("the change in copy donot change the original array",marks[0],"only copy changes",slice_view)



Marks of each student (student * marks) : [[68 85 94 83 76]
 [64 82 61 50 60]
 [82 99 79 62 68]
 [89 75 99 86 69]]
Student1 has score [68 85 94 83 76]
Student2 has score [64 82 61 50 60]
Student3 has score [82 99 79 62 68]
Student4 has score [89 75 99 86 69]
Subject wise or column wise  average marks of students are: [75.75 85.25 83.25 70.25 68.25]
Student 4 has top score 418
Marks of all the student =  [[ 73  90  99  88  81]
 [ 69  87  66  55  65]
 [ 87 100  84  67  73]
 [ 94  80 100  91  74]]
The slice of the marks array is [68 85 94 83 76]
Now see the changes in the original marks array [68 83 94 83 76]  
So the slice_view is the view and it values changes
the change in copy donot change the original array [68 83 94 83 76] only copy changes [88 94 83]
